# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\uiDesign\messenger_change_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ChangePassword(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(299, 230)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 301, 231))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QFrame{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color: white;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.changePasswordLabel = QtWidgets.QLabel(self.frame)
        self.changePasswordLabel.setGeometry(QtCore.QRect(20, 8, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.changePasswordLabel.setFont(font)
        self.changePasswordLabel.setStyleSheet("")
        self.changePasswordLabel.setObjectName("changePasswordLabel")
        self.closeButton = QtWidgets.QPushButton(self.frame)
        self.closeButton.setGeometry(QtCore.QRect(270, 3, 31, 31))
        self.closeButton.setStyleSheet('''QPushButton{border:none;
                                      background-image : url(Windows/Resources/close.png);
                                      background-repeat: no-repeat;
                                      background-position: center;} 
                                      
                                      QPushButton:hover{background-image : url(Windows/Resources/close_hover.png);
                                      background-repeat: no-repeat;
                                      background-position: center;
                                      background-color: red;}''')
        self.closeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("design\\uiDesign\\../code/Resources/close4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon)
        self.closeButton.setIconSize(QtCore.QSize(30, 30))
        self.closeButton.setObjectName("closeButton")
        self.oldPasswordLineEdit = QtWidgets.QLineEdit(self.frame)
        self.oldPasswordLineEdit.setGeometry(QtCore.QRect(0, 70, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        self.oldPasswordLineEdit.setFont(font)
        self.oldPasswordLineEdit.setStyleSheet('''QLineEdit{border-radius: 1px;
                                                  background-color: rgb(38, 28, 70);
                                                  color:white;
                                                  text-align: left;
                                                  padding: 0% 15%;}
                                                  QLineEdit:hover{background-color: rgb(85, 68, 139);
                                                  border-bottom: solid white;}''')
        self.oldPasswordLineEdit.setObjectName("oldPasswordLineEdit")
        self.newPasswordLineEdit = QtWidgets.QLineEdit(self.frame)
        self.newPasswordLineEdit.setGeometry(QtCore.QRect(0, 130, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        self.newPasswordLineEdit.setFont(font)
        self.newPasswordLineEdit.setStyleSheet("QLineEdit{\n"
"border-radius:1px;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: left;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.newPasswordLineEdit.setObjectName("newPasswordLineEdit")
        self.cancelButton = QtWidgets.QPushButton(self.frame)
        self.cancelButton.setGeometry(QtCore.QRect(10, 190, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("QPushButton{\n"
"border-radius:1px;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.cancelButton.setIconSize(QtCore.QSize(30, 30))
        self.cancelButton.setObjectName("cancelButton")
        self.saveButton = QtWidgets.QPushButton(self.frame)
        self.saveButton.setGeometry(QtCore.QRect(220, 190, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("QPushButton{\n"
"border-radius:1px;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.saveButton.setIconSize(QtCore.QSize(30, 30))
        self.saveButton.setObjectName("saveButton")
        self.oldPasswordLabel = QtWidgets.QLabel(self.frame)
        self.oldPasswordLabel.setGeometry(QtCore.QRect(16, 48, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(10)
        self.oldPasswordLabel.setFont(font)
        self.oldPasswordLabel.setStyleSheet("QLabel{\n"
"color: #75699c;\n"
"}")
        self.oldPasswordLabel.setObjectName("oldPasswordLabel")
        self.newPasswordLabel = QtWidgets.QLabel(self.frame)
        self.newPasswordLabel.setGeometry(QtCore.QRect(16, 108, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(10)
        self.newPasswordLabel.setFont(font)
        self.newPasswordLabel.setStyleSheet("QLabel{\n"
"color: #75699c;\n"
"}")
        self.newPasswordLabel.setObjectName("newPasswordLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.changePasswordLabel.setText(_translate("Dialog", "Change Password"))
        self.oldPasswordLineEdit.setPlaceholderText(_translate("Dialog", "Enter your old password"))
        self.newPasswordLineEdit.setPlaceholderText(_translate("Dialog", "Enter your new password"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.saveButton.setText(_translate("Dialog", "Save"))
        self.oldPasswordLabel.setText(_translate("Dialog", "Old Password"))
        self.newPasswordLabel.setText(_translate("Dialog", "New Password"))
