# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\uiDesign\messenger_chat_members.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ChatMembers(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(332, 560)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 330, 561))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"  border: none;\n"
"  top:-1px; \n"
"background-color: rgb(38, 28, 70); \n"
"} \n"
"\n"
"QTabBar::tab {\n"
"height: 10px;\n"
" background-color: #45357a;\n"
"color:white;\n"
"  border: none;\n"
"  padding: 15px;\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"background-color: #8B7EC1;\n"
"  margin-bottom: -1px; \n"
"color:black;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_5 = QtWidgets.QFrame(self.tab)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 331, 521))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.frame_5.setFont(font)
        self.frame_5.setStyleSheet("QFrame{\n"
"border: none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color: white;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.addToChatLabel_2 = QtWidgets.QLabel(self.frame_5)
        self.addToChatLabel_2.setGeometry(QtCore.QRect(10, 14, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.addToChatLabel_2.setFont(font)
        self.addToChatLabel_2.setStyleSheet("")
        self.addToChatLabel_2.setObjectName("addToChatLabel_2")
        self.closeButton = QtWidgets.QPushButton(self.frame_5)
        self.closeButton.setGeometry(QtCore.QRect(20, 480, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.closeButton.setFont(font)
        self.closeButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.closeButton.setIconSize(QtCore.QSize(30, 30))
        self.closeButton.setObjectName("closeButton")
        self.membersListWidget = QtWidgets.QListWidget(self.frame_5)
        self.membersListWidget.setGeometry(QtCore.QRect(10, 50, 311, 381))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.membersListWidget.setFont(font)
        self.membersListWidget.setStyleSheet('''QListWidget{
                                                background-color: rgb(38, 28, 70);
                                                border: none;}
                                                QListWidget::item {
                                                color: white;
                                                border: none;
                                                padding: 10px 0px 10px 10px;
                                                word-wrap: break-all;}
                                                QListWidget::item:selected {
                                                border: none;
                                                background-color: #45357a;
                                                color: white;
                                                padding: 0px 0px 10px 10px;
                                                word-wrap: break-all;}
                                                QListView {
                                                outline: 0;
                                                }''')
        self.membersListWidget.setObjectName("membersListWidget")
        self.deleteFromChatButton = QtWidgets.QPushButton(self.frame_5)
        self.deleteFromChatButton.setGeometry(QtCore.QRect(170, 480, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.deleteFromChatButton.setFont(font)
        self.deleteFromChatButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.deleteFromChatButton.setIconSize(QtCore.QSize(30, 30))
        self.deleteFromChatButton.setObjectName("deleteFromChatButton")
        self.makeAdminButton = QtWidgets.QPushButton(self.frame_5)
        self.makeAdminButton.setGeometry(QtCore.QRect(10, 440, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.makeAdminButton.setFont(font)
        self.makeAdminButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.makeAdminButton.setIconSize(QtCore.QSize(30, 30))
        self.makeAdminButton.setObjectName("makeAdminButton")
        self.restrictUserButton = QtWidgets.QPushButton(self.frame_5)
        self.restrictUserButton.setGeometry(QtCore.QRect(200, 440, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.restrictUserButton.setFont(font)
        self.restrictUserButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.restrictUserButton.setIconSize(QtCore.QSize(30, 30))
        self.restrictUserButton.setObjectName("restrictUserButton")
        self.tabWidget.addTab(self.tab, "")
        self.adminsTab = QtWidgets.QWidget()
        self.adminsTab.setObjectName("adminsTab")
        self.frame_6 = QtWidgets.QFrame(self.adminsTab)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 331, 521))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.frame_6.setFont(font)
        self.frame_6.setStyleSheet("QFrame{\n"
"border: none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color: white;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.adminsLabel = QtWidgets.QLabel(self.frame_6)
        self.adminsLabel.setGeometry(QtCore.QRect(10, 14, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.adminsLabel.setFont(font)
        self.adminsLabel.setStyleSheet("")
        self.adminsLabel.setObjectName("adminsLabel")
        self.closeButton_2 = QtWidgets.QPushButton(self.frame_6)
        self.closeButton_2.setGeometry(QtCore.QRect(10, 480, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.closeButton_2.setFont(font)
        self.closeButton_2.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.closeButton_2.setIconSize(QtCore.QSize(30, 30))
        self.closeButton_2.setObjectName("closeButton_2")
        self.adminsWidgetList = QtWidgets.QListWidget(self.frame_6)
        self.adminsWidgetList.setGeometry(QtCore.QRect(10, 50, 311, 421))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.adminsWidgetList.setFont(font)
        self.adminsWidgetList.setStyleSheet('''QListWidget{
                                                background-color: rgb(38, 28, 70);
                                                border: none;}
                                                QListWidget::item {
                                                color: white;
                                                border: none;
                                                padding: 10px 0px 10px 10px;
                                                word-wrap: break-all;}
                                                QListWidget::item:selected {
                                                border: none;
                                                background-color: #45357a;
                                                color: white;
                                                padding: 0px 0px 10px 10px;
                                                word-wrap: break-all;}
                                                QListView {
                                                outline: 0;
                                                }''')
        self.adminsWidgetList.setObjectName("adminsWidgetList")
        self.removeAdminButton = QtWidgets.QPushButton(self.frame_6)
        self.removeAdminButton.setGeometry(QtCore.QRect(170, 480, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.removeAdminButton.setFont(font)
        self.removeAdminButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.removeAdminButton.setIconSize(QtCore.QSize(30, 30))
        self.removeAdminButton.setObjectName("removeAdminButton")
        self.tabWidget.addTab(self.adminsTab, "")
        self.mutedTab = QtWidgets.QWidget()
        self.mutedTab.setObjectName("mutedTab")
        self.frame_7 = QtWidgets.QFrame(self.mutedTab)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 331, 521))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.frame_7.setFont(font)
        self.frame_7.setStyleSheet("QFrame{\n"
"border: none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color: white;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.restrictedUsersLabel = QtWidgets.QLabel(self.frame_7)
        self.restrictedUsersLabel.setGeometry(QtCore.QRect(10, 14, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.restrictedUsersLabel.setFont(font)
        self.restrictedUsersLabel.setStyleSheet("")
        self.restrictedUsersLabel.setObjectName("restrictedUsersLabel")
        self.closeButton_3 = QtWidgets.QPushButton(self.frame_7)
        self.closeButton_3.setGeometry(QtCore.QRect(20, 480, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.closeButton_3.setFont(font)
        self.closeButton_3.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.closeButton_3.setIconSize(QtCore.QSize(30, 30))
        self.closeButton_3.setObjectName("closeButton_3")
        self.mutedMembersListWidget = QtWidgets.QListWidget(self.frame_7)
        self.mutedMembersListWidget.setGeometry(QtCore.QRect(10, 50, 311, 421))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.mutedMembersListWidget.setFont(font)
        self.mutedMembersListWidget.setStyleSheet('''QListWidget{
                                                background-color: rgb(38, 28, 70);
                                                border: none;}
                                                QListWidget::item {
                                                color: white;
                                                border: none;
                                                padding: 10px 0px 10px 10px;
                                                word-wrap: break-all;}
                                                QListWidget::item:selected {
                                                border: none;
                                                background-color: #45357a;
                                                color: white;
                                                padding: 0px 0px 10px 10px;
                                                word-wrap: break-all;}
                                                QListView {
                                                outline: 0;
                                                }''')
        self.mutedMembersListWidget.setObjectName("mutedMembersListWidget")
        self.removeRestrictionButton = QtWidgets.QPushButton(self.frame_7)
        self.removeRestrictionButton.setGeometry(QtCore.QRect(150, 480, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.removeRestrictionButton.setFont(font)
        self.removeRestrictionButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.removeRestrictionButton.setIconSize(QtCore.QSize(30, 30))
        self.removeRestrictionButton.setObjectName("removeRestrictionButton")
        self.tabWidget.addTab(self.mutedTab, "")
        self.addToChatTab = QtWidgets.QWidget()
        self.addToChatTab.setObjectName("addToChatTab")
        self.frame_4 = QtWidgets.QFrame(self.addToChatTab)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 331, 551))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.frame_4.setFont(font)
        self.frame_4.setStyleSheet("QFrame{\n"
"border: none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color: white;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.addToChatLabel = QtWidgets.QLabel(self.frame_4)
        self.addToChatLabel.setGeometry(QtCore.QRect(10, 14, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.addToChatLabel.setFont(font)
        self.addToChatLabel.setStyleSheet("")
        self.addToChatLabel.setObjectName("addToChatLabel")
        self.closeButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.closeButton_4.setGeometry(QtCore.QRect(130, 480, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.closeButton_4.setFont(font)
        self.closeButton_4.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.closeButton_4.setIconSize(QtCore.QSize(30, 30))
        self.closeButton_4.setObjectName("closeButton_4")
        self.contactsListWidget = QtWidgets.QListWidget(self.frame_4)
        self.contactsListWidget.setGeometry(QtCore.QRect(10, 50, 311, 421))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.contactsListWidget.setFont(font)
        self.contactsListWidget.setStyleSheet('''QListWidget{
                                                background-color: rgb(38, 28, 70);
                                                border: none;}
                                                QListWidget::item {
                                                color: white;
                                                border: none;
                                                padding: 10px 0px 10px 10px;
                                                word-wrap: break-all;}
                                                QListWidget::item:selected {
                                                border: none;
                                                background-color: #45357a;
                                                color: white;
                                                padding: 0px 0px 10px 10px;
                                                word-wrap: break-all;}
                                                QListView {
                                                outline: 0;
                                                }''')
        self.contactsListWidget.setObjectName("contactsListWidget")
        self.addToChatButton = QtWidgets.QPushButton(self.frame_4)
        self.addToChatButton.setGeometry(QtCore.QRect(200, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.addToChatButton.setFont(font)
        self.addToChatButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.addToChatButton.setIconSize(QtCore.QSize(30, 30))
        self.addToChatButton.setObjectName("addToChatButton")
        self.tabWidget.addTab(self.addToChatTab, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addToChatLabel_2.setText(_translate("Form", "Chat Members"))
        self.closeButton.setText(_translate("Form", "Close"))
        self.deleteFromChatButton.setText(_translate("Form", "Delete from Chat"))
        self.makeAdminButton.setText(_translate("Form", "Make admin"))
        self.restrictUserButton.setText(_translate("Form", "Restrict"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Members"))
        self.adminsLabel.setText(_translate("Form", "Admins"))
        self.closeButton_2.setText(_translate("Form", "Close"))
        self.removeAdminButton.setText(_translate("Form", "Remove Admin"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.adminsTab), _translate("Form", "Admins"))
        self.restrictedUsersLabel.setText(_translate("Form", "Restricted Users"))
        self.closeButton_3.setText(_translate("Form", "Close"))
        self.removeRestrictionButton.setText(_translate("Form", "Remove Restriction"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mutedTab), _translate("Form", "Muted"))
        self.addToChatLabel.setText(_translate("Form", "Add to Chat Room"))
        self.closeButton_4.setText(_translate("Form", "Close"))
        self.addToChatButton.setText(_translate("Form", "Add To Chat"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.addToChatTab), _translate("Form", "Add to Chat"))
