# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\uiDesign\messenger_contacts.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Contacts(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(374, 518)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 330, 531))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"  border: none;\n"
"  top:-1px; \n"
"background-color: rgb(38, 28, 70); \n"
"} \n"
"\n"
"QTabBar::tab {\n"
"height: 10px;\n"
" background-color: #45357a;\n"
"color:white;\n"
"  border: none;\n"
"  padding: 15px;\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"background-color: #8B7EC1;\n"
"  margin-bottom: -1px; \n"
"color:black;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.contactsTab = QtWidgets.QWidget()
        self.contactsTab.setObjectName("contactsTab")
        self.frame = QtWidgets.QFrame(self.contactsTab)
        self.frame.setGeometry(QtCore.QRect(0, 0, 331, 471))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QFrame{\n"
"border: none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color: white;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.friendsLabel = QtWidgets.QLabel(self.frame)
        self.friendsLabel.setGeometry(QtCore.QRect(10, 14, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.friendsLabel.setFont(font)
        self.friendsLabel.setStyleSheet("")
        self.friendsLabel.setObjectName("friendsLabel")
        self.closeButton = QtWidgets.QPushButton(self.frame)
        self.closeButton.setGeometry(QtCore.QRect(130, 430, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.closeButton.setFont(font)
        self.closeButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.closeButton.setIconSize(QtCore.QSize(30, 30))
        self.closeButton.setObjectName("closeButton")
        self.contactsListWidget = QtWidgets.QListWidget(self.frame)
        self.contactsListWidget.setGeometry(QtCore.QRect(10, 90, 311, 331))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.contactsListWidget.setFont(font)
        self.contactsListWidget.setStyleSheet('''QListWidget{
                                                background-color: rgb(38, 28, 70);
                                                border: none;}
                                                QListWidget::item {
                                                color: white;
                                                border: none;
                                                padding: 10px 0px 10px 10px;
                                                word-wrap: break-all;}
                                                QListWidget::item:selected {
                                                border: none;
                                                background-color: #45357a;
                                                color: white;
                                                padding: 0px 0px 10px 10px;
                                                word-wrap: break-all;}
                                                QListView {
                                                outline: 0;
                                                }''')
        self.contactsListWidget.setObjectName("contactsListWidget")
        self.deleteContactButton = QtWidgets.QPushButton(self.frame)
        self.deleteContactButton.setGeometry(QtCore.QRect(10, 50, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.deleteContactButton.setFont(font)
        self.deleteContactButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.deleteContactButton.setIconSize(QtCore.QSize(30, 30))
        self.deleteContactButton.setObjectName("deleteContactButton")
        self.blockButton = QtWidgets.QPushButton(self.frame)
        self.blockButton.setGeometry(QtCore.QRect(250, 50, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.blockButton.setFont(font)
        self.blockButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.blockButton.setIconSize(QtCore.QSize(30, 30))
        self.blockButton.setObjectName("blockButton")
        self.tabWidget.addTab(self.contactsTab, "")
        self.blockedTab = QtWidgets.QWidget()
        self.blockedTab.setObjectName("blockedTab")
        self.frame_2 = QtWidgets.QFrame(self.blockedTab)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 331, 471))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("QFrame{\n"
"border: none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color: white;\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.blockedLabel = QtWidgets.QLabel(self.frame_2)
        self.blockedLabel.setGeometry(QtCore.QRect(10, 14, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.blockedLabel.setFont(font)
        self.blockedLabel.setStyleSheet("")
        self.blockedLabel.setObjectName("blockedLabel")
        self.closeButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.closeButton_2.setGeometry(QtCore.QRect(130, 430, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.closeButton_2.setFont(font)
        self.closeButton_2.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.closeButton_2.setIconSize(QtCore.QSize(30, 30))
        self.closeButton_2.setObjectName("closeButton_2")
        self.blockedListWidget = QtWidgets.QListWidget(self.frame_2)
        self.blockedListWidget.setGeometry(QtCore.QRect(10, 50, 311, 371))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.blockedListWidget.setFont(font)
        self.blockedListWidget.setStyleSheet('''QListWidget{
                                                background-color: rgb(38, 28, 70);
                                                border: none;}
                                                QListWidget::item {
                                                color: white;
                                                border: none;
                                                padding: 10px 0px 10px 10px;
                                                word-wrap: break-all;}
                                                QListWidget::item:selected {
                                                border: none;
                                                background-color: #45357a;
                                                color: white;
                                                padding: 0px 0px 10px 10px;
                                                word-wrap: break-all;}
                                                QListView {
                                                outline: 0;
                                                }''')
        self.blockedListWidget.setObjectName("blockedListWidget")
        self.unblockButton = QtWidgets.QPushButton(self.frame_2)
        self.unblockButton.setGeometry(QtCore.QRect(220, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.unblockButton.setFont(font)
        self.unblockButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.unblockButton.setIconSize(QtCore.QSize(30, 30))
        self.unblockButton.setObjectName("unblockButton")
        self.tabWidget.addTab(self.blockedTab, "")
        self.SearchTab = QtWidgets.QWidget()
        self.SearchTab.setObjectName("SearchTab")
        self.frame_3 = QtWidgets.QFrame(self.SearchTab)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 331, 491))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("QFrame{\n"
"border: none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color: white;\n"
"\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.searchLabel = QtWidgets.QLabel(self.frame_3)
        self.searchLabel.setGeometry(QtCore.QRect(10, 14, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.searchLabel.setFont(font)
        self.searchLabel.setStyleSheet("")
        self.searchLabel.setObjectName("searchLabel")
        self.closeButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.closeButton_3.setGeometry(QtCore.QRect(10, 430, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.closeButton_3.setFont(font)
        self.closeButton_3.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.closeButton_3.setIconSize(QtCore.QSize(30, 30))
        self.closeButton_3.setObjectName("closeButton_3")
        self.addContactButton = QtWidgets.QPushButton(self.frame_3)
        self.addContactButton.setGeometry(QtCore.QRect(200, 430, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.addContactButton.setFont(font)
        self.addContactButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.addContactButton.setIconSize(QtCore.QSize(30, 30))
        self.addContactButton.setObjectName("addContactPushButton_2")
        self.searchLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.searchLineEdit.setGeometry(QtCore.QRect(10, 50, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.searchLineEdit.setFont(font)
        self.searchLineEdit.setStyleSheet('''QLineEdit{
                                             border-radius: 5px;
                                             background-color: #45357a;
                                             color: white;
                                             padding: 0px 10px;}''')
        self.searchLineEdit.setObjectName("searchLabel_2")
        self.usernameLabel = QtWidgets.QLabel(self.frame_3)
        self.usernameLabel.setGeometry(QtCore.QRect(20, 130, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setStyleSheet("")
        self.usernameLabel.setObjectName("usernameLabel")
        self.findButton = QtWidgets.QPushButton(self.frame_3)
        self.findButton.setGeometry(QtCore.QRect(290, 50, 31, 31))
        self.findButton.setStyleSheet('''QPushButton{border-radius: 15px;
                                      background-image : url(Windows/Resources/search.png);
                                      background-repeat: no-repeat;
                                      background-position: center;} 

                                      QPushButton:hover{background-image : url(Windows/Resources/search_hover.png);
                                      background-repeat: no-repeat;
                                      background-position: center;
                                      }''')
        self.findButton.setText("")
        self.findButton.setObjectName("findButton")
        self.tabWidget.addTab(self.SearchTab, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.friendsLabel.setText(_translate("Form", "Friends"))
        self.closeButton.setText(_translate("Form", "Close"))
        self.deleteContactButton.setText(_translate("Form", "Delete"))
        self.blockButton.setText(_translate("Form", "Block"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.contactsTab), _translate("Form", "Contacts"))
        self.blockedLabel.setText(_translate("Form", "Blocked"))
        self.closeButton_2.setText(_translate("Form", "Close"))
        self.unblockButton.setText(_translate("Form", "Unblock"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.blockedTab), _translate("Form", "Blocked"))
        self.searchLabel.setText(_translate("Form", "Search"))
        self.closeButton_3.setText(_translate("Form", "Close"))
        self.addContactButton.setText(_translate("Form", "Add Contact"))
        self.searchLineEdit.setPlaceholderText(_translate("Form", "Search"))
        self.usernameLabel.setText(_translate("Form", "USERNAME"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SearchTab), _translate("Form", "Search"))
