# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\uiDesign\messenger_modal_create_chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class CreateChat(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(304, 163)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 301, 161))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QFrame{\n"
"border: none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color: white;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.createChatLabel = QtWidgets.QLabel(self.frame)
        self.createChatLabel.setGeometry(QtCore.QRect(10, 10, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.createChatLabel.setFont(font)
        self.createChatLabel.setStyleSheet("")
        self.createChatLabel.setObjectName("createChatLabel")
        self.closeButton = QtWidgets.QPushButton(self.frame)
        self.closeButton.setGeometry(QtCore.QRect(270, 3, 31, 31))
        self.closeButton.setStyleSheet('''QPushButton{border:none;
                                      background-image : url(Windows/Resources/close.png);
                                      background-repeat: no-repeat;
                                      background-position: center;} 
                                      
                                      QPushButton:hover{background-image : url(Windows/Resources/close_hover.png);
                                      background-repeat: no-repeat;
                                      background-position: center;
                                      background-color: red;}''')
        self.closeButton.setText("")
        self.closeButton.setObjectName("pushButton_5")
        self.chatNameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.chatNameLineEdit.setGeometry(QtCore.QRect(0, 70, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        self.chatNameLineEdit.setFont(font)
        self.chatNameLineEdit.setStyleSheet("QLineEdit{\n"
"border-radius: 1px;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: left;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"border-bottom: solid white;\n"
"}\n"
"")
        self.chatNameLineEdit.setText("")
        self.chatNameLineEdit.setObjectName("chatNameLineEdit")
        self.cancelButton = QtWidgets.QPushButton(self.frame)
        self.cancelButton.setGeometry(QtCore.QRect(10, 120, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("QPushButton{\n"
"border-radius:1px;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.cancelButton.setIconSize(QtCore.QSize(30, 30))
        self.cancelButton.setObjectName("cancelButton")
        self.saveButton = QtWidgets.QPushButton(self.frame)
        self.saveButton.setGeometry(QtCore.QRect(230, 120, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("QPushButton{\n"
"border-radius:1px;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.saveButton.setIconSize(QtCore.QSize(30, 30))
        self.saveButton.setObjectName("saveButton")
        self.chatNameLabel = QtWidgets.QLabel(self.frame)
        self.chatNameLabel.setGeometry(QtCore.QRect(16, 48, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(10)
        self.chatNameLabel.setFont(font)
        self.chatNameLabel.setStyleSheet("QLabel{\n"
"color: #75699c;\n"
"}")
        self.chatNameLabel.setObjectName("chatNameLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.createChatLabel.setText(_translate("Dialog", "Create Chat Room"))
        self.chatNameLineEdit.setPlaceholderText(_translate("Dialog", "Enter a chat name"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.saveButton.setText(_translate("Dialog", "Save"))
        self.chatNameLabel.setText(_translate("Dialog", "Chat Name"))
