# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\uiDesign\messenger_edit_profile_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class EditProfile(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(301, 269)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 301, 271))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QFrame{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color: white;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.editProfileLabel = QtWidgets.QLabel(self.frame)
        self.editProfileLabel.setGeometry(QtCore.QRect(20, 8, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.editProfileLabel.setFont(font)
        self.editProfileLabel.setStyleSheet("")
        self.editProfileLabel.setObjectName("editProfileLabel")
        self.closeButton = QtWidgets.QPushButton(self.frame)
        self.closeButton.setGeometry(QtCore.QRect(270, 0, 31, 31))
        self.closeButton.setStyleSheet('''QPushButton{border:none;
                                      background-image : url(Windows/Resources/close.png);
                                      background-repeat: no-repeat;
                                      background-position: center;} 
                                      
                                      QPushButton:hover{background-image : url(Windows/Resources/close_hover.png);
                                      background-repeat: no-repeat;
                                      background-position: center;
                                      background-color: red;}''')
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.usernameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.usernameLineEdit.setGeometry(QtCore.QRect(0, 70, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        self.usernameLineEdit.setFont(font)
        self.usernameLineEdit.setStyleSheet("QLineEdit{\n"
"border-radius: 1px;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: left;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"border-bottom: solid white;\n"
"}\n"
"")
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.emailLineEdit = QtWidgets.QLineEdit(self.frame)
        self.emailLineEdit.setGeometry(QtCore.QRect(0, 130, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        self.emailLineEdit.setFont(font)
        self.emailLineEdit.setStyleSheet("QLineEdit{\n"
"border-radius:1px;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: left;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.cancelButton = QtWidgets.QPushButton(self.frame)
        self.cancelButton.setGeometry(QtCore.QRect(10, 230, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("QPushButton{\n"
"border-radius:1px;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.cancelButton.setIconSize(QtCore.QSize(30, 30))
        self.cancelButton.setObjectName("cancelButton")
        self.saveButton = QtWidgets.QPushButton(self.frame)
        self.saveButton.setGeometry(QtCore.QRect(230, 230, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("QPushButton{\n"
"border-radius:1px;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.saveButton.setIconSize(QtCore.QSize(30, 30))
        self.saveButton.setObjectName("saveButton")
        self.usernameLabel = QtWidgets.QLabel(self.frame)
        self.usernameLabel.setGeometry(QtCore.QRect(16, 48, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(10)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setStyleSheet("QLabel{\n"
"color: #75699c;\n"
"}")
        self.usernameLabel.setObjectName("usernameLabel")
        self.emailLabel = QtWidgets.QLabel(self.frame)
        self.emailLabel.setGeometry(QtCore.QRect(16, 108, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(10)
        self.emailLabel.setFont(font)
        self.emailLabel.setStyleSheet("QLabel{\n"
"color: #75699c;\n"
"}")
        self.emailLabel.setObjectName("emailLabel")
        self.changePasswordButton = QtWidgets.QPushButton(self.frame)
        self.changePasswordButton.setGeometry(QtCore.QRect(60, 185, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.changePasswordButton.setFont(font)
        self.changePasswordButton.setStyleSheet("QPushButton{\n"
"border-radius:1px;\n"
"    background-color: rgb(38, 28, 70);\n"
"color:white;\n"
"text-align: center;\n"
"padding: 0% 15%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 68, 139);\n"
"}\n"
"")
        self.changePasswordButton.setIconSize(QtCore.QSize(30, 30))
        self.changePasswordButton.setObjectName("cancelButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.editProfileLabel.setText(_translate("Form", "Edit Profile"))
        self.usernameLineEdit.setPlaceholderText(_translate("Form", "Enter your new user name"))
        self.emailLineEdit.setPlaceholderText(_translate("Form", "Enter your new email"))
        self.cancelButton.setText(_translate("Form", "Cancel"))
        self.saveButton.setText(_translate("Form", "Save"))
        self.usernameLabel.setText(_translate("Form", "User Name"))
        self.emailLabel.setText(_translate("Form", "Email"))
        self.changePasswordButton.setText(_translate("Form", "Change Password"))
