# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\uiDesign\messenger_mainpage_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 709)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 20, 1102, 691))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(360, 175, 381, 291))
        self.frame_2.setStyleSheet("QFrame{\n"
"border : 5px solid #f5f5f5;\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.usernameLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.usernameLineEdit.setGeometry(QtCore.QRect(44, 40, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(10)
        self.usernameLineEdit.setFont(font)
        self.usernameLineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(245, 245, 245);\n"
"border-radius: 1px;\n"
"padding: 0% 10%;\n"
"}")
        self.usernameLineEdit.setMaxLength(25)
        self.usernameLineEdit.setObjectName("lineEdit_3")
        self.passwordLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.passwordLineEdit.setGeometry(QtCore.QRect(44, 120, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(10)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(245, 245, 245);\n"
"border-radius: 1px;\n"
"padding: 0% 10%;\n"
"}")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("lineEdit_5")
        self.loginButton = QtWidgets.QPushButton(self.frame_2)
        self.loginButton.setGeometry(QtCore.QRect(134, 190, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet('''QPushButton{border-radius: 7px;
                                      color: white;
                                      background-color: #6538b9} 
                                      
                                      QPushButton:hover{;
                                      background-position: center;
                                      background-color: #45357a;}''')

        self.loginButton.setObjectName("pushButton_15")
        self.usernameLabel = QtWidgets.QLabel(self.frame_2)
        self.usernameLabel.setGeometry(QtCore.QRect(50, 72, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Arabic UI")
        self.usernameLabel.setFont(font)
        self.usernameLabel.setStyleSheet("QLabel{\n"
"border :none;\n"
"color: #979799;\n"
"}")
        self.usernameLabel.setObjectName("label_2")
        self.passwordLabel = QtWidgets.QLabel(self.frame_2)
        self.passwordLabel.setGeometry(QtCore.QRect(50, 152, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Arabic UI")
        self.passwordLabel.setFont(font)
        self.passwordLabel.setStyleSheet("QLabel{\n"
"border :none;\n"
"color: #979799;\n"
"}")
        self.passwordLabel.setObjectName("label_3")
        self.createAccountLabel = QtWidgets.QLabel(self.frame_2)
        self.createAccountLabel.setGeometry(QtCore.QRect(80, 250, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(9)
        self.createAccountLabel.setFont(font)
        self.createAccountLabel.setStyleSheet("QLabel{\n"
"border :none;\n"
"color: #979799;\n"
"}")
        self.createAccountLabel.setObjectName("label_4")
        self.registerButton = QtWidgets.QPushButton(self.frame_2)
        self.registerButton.setGeometry(QtCore.QRect(215, 249, 71, 23))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(9)
        self.registerButton.setFont(font)
        self.registerButton.setStyleSheet('''QPushButton{border-radius: 7px;
                                             color: #6538b9;}
                                             QPushButton:hover{
                                             color: #45357a;}
                                             }''')
        self.registerButton.setObjectName("pushButton")
        self.loginLabel = QtWidgets.QLabel(self.frame)
        self.loginLabel.setGeometry(QtCore.QRect(520, 120, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(18)
        self.loginLabel.setFont(font)
        self.loginLabel.setStyleSheet("QLabel{\n"
"text-align: center;\n"
"color: #6538b9;\n"
"}")
        self.loginLabel.setObjectName("label")
        self.elementPanelFrame = QtWidgets.QFrame(self.centralwidget)
        self.elementPanelFrame.setGeometry(QtCore.QRect(0, 0, 1101, 25))
        self.elementPanelFrame.setStyleSheet("background-color: rgb(38, 28, 70);")
        self.elementPanelFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.elementPanelFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.elementPanelFrame.setObjectName("frame_5")
        self.closeButton = QtWidgets.QPushButton(self.elementPanelFrame)
        self.closeButton.setGeometry(QtCore.QRect(1066, 0, 35, 25))
        self.closeButton.setStyleSheet('''QPushButton{border-radius: 15px;
                                      background-image : url(Windows/Resources/close.png);
                                      background-repeat: no-repeat;
                                      background-position: center;} 
                                      
                                      QPushButton:hover{background-image : url(Windows/Resources/close_hover.png);
                                      background-repeat: no-repeat;
                                      background-position: center;
                                      background-color: red;}''')
        self.closeButton.setText("")
        self.closeButton.setObjectName("pushButton_12")
        self.minimizeButton = QtWidgets.QPushButton(self.elementPanelFrame)
        self.minimizeButton.setGeometry(QtCore.QRect(996, 0, 35, 25))
        self.minimizeButton.setStyleSheet('''QPushButton{border-radius: 15px;
                                      background-image : url(Windows/Resources/minimize.png);
                                      background-repeat: no-repeat;
                                      background-position: center;} 
                                      
                                      QPushButton:hover{background-image : url(Windows/Resources/minimize_hover.png);
                                      background-repeat: no-repeat;
                                      background-position: center;
                                      background-color: #45357a;}''')
        self.minimizeButton.setText("")
        self.minimizeButton.setObjectName("pushButton_13")
        self.maximizeButton = QtWidgets.QPushButton(self.elementPanelFrame)
        self.maximizeButton.setGeometry(QtCore.QRect(1031, 0, 35, 25))
        self.maximizeButton.setStyleSheet('''QPushButton{border-radius: 15px;
                                      background-image : url(Windows/Resources/maximize.png);
                                      background-repeat: no-repeat;
                                      background-position: center;} 
                                      
                                      QPushButton:hover{background-image : url(Windows/Resources/maximize_hover.png);
                                      background-repeat: no-repeat;
                                      background-position: center;
                                      background-color: #45357a;}''')
        self.maximizeButton.setText("")
        self.maximizeButton.setObjectName("pushButton_14")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.usernameLineEdit.setPlaceholderText(_translate("MainWindow", "User Name"))
        self.passwordLineEdit.setPlaceholderText(_translate("MainWindow", "Password"))
        self.loginButton.setText(_translate("MainWindow", "Sign In"))
        self.usernameLabel.setText(_translate("MainWindow", "Max 25 characters"))
        self.passwordLabel.setText(_translate("MainWindow", "Min 8 characters"))
        self.createAccountLabel.setText(_translate("MainWindow", "Don\'t have an Account?"))
        self.registerButton.setText(_translate("MainWindow", "Registration"))
        self.loginLabel.setText(_translate("MainWindow", "Login"))
