# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\uiDesign\messenger_mainpage_registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Registration(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 711)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 20, 1101, 691))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(360, 175, 381, 361))
        self.frame_2.setStyleSheet("QFrame{\n"
"border : 5px solid #f5f5f5;\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.usernameLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.usernameLineEdit.setGeometry(QtCore.QRect(44, 40, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(10)
        self.usernameLineEdit.setFont(font)
        self.usernameLineEdit.setStyleSheet('''QLineEdit{ 
                                               background-color: rgb(245, 245, 245);
                                               border-radius: 1px; padding: 0% 10%;}''')
        self.usernameLineEdit.setMaxLength(25)
        self.usernameLineEdit.setObjectName("lineEdit_3")
        self.emailLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.emailLineEdit.setGeometry(QtCore.QRect(44, 120, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(10)
        self.emailLineEdit.setFont(font)
        self.emailLineEdit.setStyleSheet('''QLineEdit{ 
                                               background-color: rgb(245, 245, 245);
                                               border-radius: 1px; padding: 0% 10%;}''')
        self.emailLineEdit.setObjectName("lineEdit_4")
        self.passwordLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.passwordLineEdit.setGeometry(QtCore.QRect(44, 200, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(10)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setStyleSheet('''QLineEdit{ 
                                               background-color: rgb(245, 245, 245);
                                               border-radius: 1px; padding: 0% 10%;}''')
        self.passwordLineEdit.setObjectName("lineEdit_5")
        self.registerButton = QtWidgets.QPushButton(self.frame_2)
        self.registerButton.setGeometry(QtCore.QRect(134, 290, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        self.registerButton.setFont(font)
        self.registerButton.setStyleSheet('''QPushButton{border-radius: 7px;
                                      color: white;
                                      background-color: #6538b9} 
                                      
                                      QPushButton:hover{;
                                      background-position: center;
                                      background-color: #45357a;}''')
        self.registerButton.setObjectName("pushButton_15")
        self.usernameLabel = QtWidgets.QLabel(self.frame_2)
        self.usernameLabel.setGeometry(QtCore.QRect(50, 70, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Arabic UI")
        self.usernameLabel.setFont(font)
        self.usernameLabel.setStyleSheet("QLabel{\n"
"border :none;\n"
"color: #979799;\n"
"}")
        self.usernameLabel.setObjectName("label_2")
        self.passwordLabel = QtWidgets.QLabel(self.frame_2)
        self.passwordLabel.setGeometry(QtCore.QRect(50, 230, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Arabic UI")
        self.passwordLabel.setFont(font)
        self.passwordLabel.setStyleSheet("QLabel{\n"
"border :none;\n"
"color: #979799;\n"
"}")
        self.passwordLabel.setObjectName("label_3")
        self.registrationLabel = QtWidgets.QLabel(self.frame)
        self.registrationLabel.setGeometry(QtCore.QRect(485, 120, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(18)
        self.registrationLabel.setFont(font)
        self.registrationLabel.setStyleSheet("QLabel{\n"
"text-align: center;\n"
"color: #6538b9;\n"
"}")
        self.registrationLabel.setObjectName("label")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 1101, 25))
        self.frame_5.setStyleSheet("background-color: rgb(38, 28, 70);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.closeButton = QtWidgets.QPushButton(self.frame_5)
        self.closeButton.setGeometry(QtCore.QRect(1066, 0, 35, 25))
        self.closeButton.setStyleSheet('''QPushButton{border-radius: 15px;
                                      background-image : url(Windows/Resources/close.png);
                                      background-repeat: no-repeat;
                                      background-position: center;} 
                                      
                                      QPushButton:hover{background-image : url(Windows/Resources/close_hover.png);
                                      background-repeat: no-repeat;
                                      background-position: center;
                                      background-color: red;}''')
        self.closeButton.setText("")
        self.closeButton.setIconSize(QtCore.QSize(20, 20))
        self.closeButton.setObjectName("pushButton_12")
        self.minimizeButton = QtWidgets.QPushButton(self.frame_5)
        self.minimizeButton.setGeometry(QtCore.QRect(996, 0, 35, 25))
        self.minimizeButton.setStyleSheet('''QPushButton{border-radius: 15px;
                                      background-image : url(Windows/Resources/minimize.png);
                                      background-repeat: no-repeat;
                                      background-position: center;} 
                                      
                                      QPushButton:hover{background-image : url(Windows/Resources/minimize_hover.png);
                                      background-repeat: no-repeat;
                                      background-position: center;
                                      background-color: #45357a;}''')
        self.minimizeButton.setText("")
        self.minimizeButton.setIconSize(QtCore.QSize(17, 17))
        self.minimizeButton.setObjectName("pushButton_13")
        self.maximizeButton = QtWidgets.QPushButton(self.frame_5)
        self.maximizeButton.setGeometry(QtCore.QRect(1031, 0, 35, 25))
        self.maximizeButton.setStyleSheet('''QPushButton{border-radius: 15px;
                                      background-image : url(Windows/Resources/maximize.png);
                                      background-repeat: no-repeat;
                                      background-position: center;} 
                                      
                                      QPushButton:hover{background-image : url(Windows/Resources/maximize_hover.png);
                                      background-repeat: no-repeat;
                                      background-position: center;
                                      background-color: #45357a;}''')
        self.maximizeButton.setText("")
        self.maximizeButton.setIconSize(QtCore.QSize(15, 15))
        self.maximizeButton.setObjectName("pushButton_14")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.usernameLineEdit.setPlaceholderText(_translate("MainWindow", "User Name"))
        self.emailLineEdit.setPlaceholderText(_translate("MainWindow", "Enter your email"))
        self.passwordLineEdit.setPlaceholderText(_translate("MainWindow", "Password"))
        self.registerButton.setText(_translate("MainWindow", "Sign Up"))
        self.usernameLabel.setText(_translate("MainWindow", "Max 25 characters"))
        self.passwordLabel.setText(_translate("MainWindow", "Min 8 characters"))
        self.registrationLabel.setText(_translate("MainWindow", "Registration"))
