# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\uiDesign\messenger_modal_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from constants import RESOURCES_PATH


class SettingsChatWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(300, 220)
        Dialog.setModal(True)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 301, 221))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QFrame{\n"
"border:none;\n"
"    background-color: rgb(38, 28, 70);\n"
"color: white;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 50, 301, 16))
        self.frame_3.setStyleSheet("    background-color: rgb(85, 68, 139);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.settingsLabel = QtWidgets.QLabel(self.frame)
        self.settingsLabel.setGeometry(QtCore.QRect(20, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.settingsLabel.setFont(font)
        self.settingsLabel.setStyleSheet("")
        self.settingsLabel.setObjectName("settingsLabel")
        self.editProfileButton = QtWidgets.QPushButton(self.frame)
        self.editProfileButton.setGeometry(QtCore.QRect(0, 70, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.editProfileButton.setFont(font)
        self.editProfileButton.setStyleSheet('''QPushButton{border-radius:1px;
                                           background-color: rgb(38, 28, 70);
                                           color:white;
                                           text-align: left;
                                           padding: 0% 15%;}
                                           QPushButton:hover{background-color: rgb(85, 68, 139);}''')
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(RESOURCES_PATH+"profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editProfileButton.setIcon(icon)
        self.editProfileButton.setIconSize(QtCore.QSize(30, 30))
        self.editProfileButton.setObjectName("editProfileButton")
        self.contactsButton = QtWidgets.QPushButton(self.frame)
        self.contactsButton.setGeometry(QtCore.QRect(0, 105, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.contactsButton.setFont(font)
        self.contactsButton.setStyleSheet('''QPushButton{border-radius:1px;
                                           background-color: rgb(38, 28, 70);
                                           color:white;
                                           text-align: left;
                                           padding: 0% 15%;}
                                           QPushButton:hover{background-color: rgb(85, 68, 139);}''')
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("design\\uiDesign\\../code/Resources/users1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactsButton.setIcon(icon1)
        self.contactsButton.setIconSize(QtCore.QSize(30, 30))
        self.contactsButton.setObjectName("contactsButton")
        self.createChatButton = QtWidgets.QPushButton(self.frame)
        self.createChatButton.setGeometry(QtCore.QRect(0, 140, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.createChatButton.setFont(font)
        self.createChatButton.setStyleSheet('''QPushButton{border-radius:1px;
                                           background-color: rgb(38, 28, 70);
                                           color:white;
                                           text-align: left;
                                           padding: 0% 15%;}
                                           QPushButton:hover{background-color: rgb(85, 68, 139);}''')
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("design\\uiDesign\\../code/Resources/chat4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createChatButton.setIcon(icon2)
        self.createChatButton.setIconSize(QtCore.QSize(30, 30))
        self.createChatButton.setObjectName("createChatButton")
        self.logoutButton = QtWidgets.QPushButton(self.frame)
        self.logoutButton.setGeometry(QtCore.QRect(0, 175, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.logoutButton.setFont(font)
        self.logoutButton.setStyleSheet('''QPushButton{border-radius:1px;
                                           background-color: rgb(38, 28, 70);
                                           color:white;
                                           text-align: left;
                                           padding: 0% 15%;}
                                           QPushButton:hover{background-color: rgb(85, 68, 139);}''')
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("design\\uiDesign\\../code/Resources/log_out1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoutButton.setIcon(icon3)
        self.logoutButton.setIconSize(QtCore.QSize(30, 30))
        self.logoutButton.setObjectName("logoutButton")
        self.closeButton = QtWidgets.QPushButton(self.frame)
        self.closeButton.setGeometry(QtCore.QRect(269, 0, 31, 31))
        self.closeButton.setStyleSheet('''QPushButton{border: none;
                                      background-image : url(Windows/Resources/close.png);
                                      background-repeat: no-repeat;
                                      background-position: center;} 

                                      QPushButton:hover{background-image : url(Windows/Resources/close_hover.png);
                                      background-repeat: no-repeat;
                                      background-position: center;
                                      background-color: red;}''')
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.settingsLabel.setText(_translate("Dialog", "Settings"))
        self.editProfileButton.setText(_translate("Dialog", "Edit profile"))
        self.contactsButton.setText(_translate("Dialog", "Contacts"))
        self.createChatButton.setText(_translate("Dialog", "Create chat"))
        self.logoutButton.setText(_translate("Dialog", "Log out"))
